### PR TITLE
fix readme

### PR DESCRIPTION
**Pull request by paOol**
typo and `make` pre req.

### CODE REVIEW

**Comment by alwaysAn0n** [comment]
@GitCash bot send @paOol 1 usd

**Comment by GitCash** [comment]
Hey **paOol**, user **alwaysAn0n** tipped you **8264 bits** in Bitcoin Cash ( ~ **$1** ).

*[Click here to claim it!](https://gitcash.io/claim/paOol)*

You can also add the "thumbs down" reaction to **alwaysAn0n**'s comment above to prevent future tips.

**Comment by alwaysAn0n** [comment]
Hey @christroutner .  The tip needs to be on it's own line like below.

Thanks @paOol!

@GitCash bot send @paOol 1 usd

**Comment by GitCash** [comment]
Hey **paOol**, user **alwaysAn0n** tipped you **8264 bits** in Bitcoin Cash ( ~ **$1** ).

*[Click here to claim it!](https://gitcash.io/claim/paOol)*

You can also add the "thumbs down" reaction to **alwaysAn0n**'s comment above to prevent future tips.

**Comment by christroutner** [comment]
@GitCash bot send @alwaysAn0n 2 usd

Thanks for the help!

**Comment by GitCash** [comment]
Hey **alwaysAn0n**, user **christroutner** tipped you **16666 bits** in Bitcoin Cash ( ~ **$2** ).

*[Click here to claim it!](https://gitcash.io/claim/alwaysAn0n)*

You can also add the "thumbs down" reaction to **christroutner**'s comment above to prevent future tips.

**Comment by cgcardona** [comment]
:tada: This PR is included in version 1.14.7 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Pull request merged**
