### PR TITLE
New routes with POST body params

### PR DESCRIPTION
**Pull request by sambengtson**
Hey guys, couple of thoughts here

1. I'm using mocha to run the unit tests that have already been set up.  Is it normal for 11 of them to fail?
2. I have updated the wormhole-sdk.  I can successfully send transactions using these new routes
3. I will create a PR for wormhole-sdk in the morning.  I'm running on fumes right now 😄 

I know you guys are looking towards a refactor, so if you want to accomplish this another way, let me know.

Thanks.

### CODE REVIEW

**Comment by sambengtson** [comment]
I forgot to mention the swagger documentation.  If I could get a quick rundown on that, I can generate it as well.

**Comment by christroutner** [comment]
Great stuff, @sambengtson! I especially like the payload size limit. Didn't know we could specify it that easily.

As I mentioned in the chat room, this repo will be undergoing a major refactor soon. We'll use this PR at that time.

**Comment by christroutner** [comment]
@gitcash send 0.0045 BCH to @sambengtson 

Thanks, Sam!

**Comment by GitCash** [comment]
Hey **sambengtson**, user **christroutner** tipped you **4500 bits** in Bitcoin Cash ( ~ **$1.9845** ).

*[Click here to claim it!](https://gitcash.io/claim/sambengtson)*

You can also add the "thumbs down" reaction to **christroutner**'s comment above to prevent future tips.

**Comment by sambengtson** [comment]
Awesome thanks!

**Comment by Jakkon1981Boonmark** [comment]
ขอดึงกลับนะครับพอดีระบบการทำงานและออฟฟิตผมรวมทั้งบุคลากรควรต้องถึงเวลาขยายเพิ่มแล้วหล่ะ
ขอบคัณครับ

**Comment by christroutner** [comment]
Closing this PR. We've converted several endpoints to POST or PUT in the V2 refactor and will be taking it live shortly after the new year (2018 -> 2019).

**Pull request closed without merging**
